name: Pull and Save Docker Images
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'ros:jazzy'  # 设置默认的 Docker 镜像列表
      platform:
        description: '请填写docker镜像平台, linux/amd64 or linux/arm64 or else'
        required: true
        default: 'linux/amd64'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "${{ github.event.inputs.platform }}"
          docker save "${image}" -o "${image//\//_}-images.tar"
        done

    - name: Compress the TAR files
      run: tar -czf docker_images.tar.gz *-images.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: docker_images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-images.tar
